### ISSUE TITLE
inference result is different from the paper

### ISSUE THREAD

**Issue by andy690** [bearyi26/DCPT#1]
My experimental results on darktrack2021 are shown below, significantly higher than those in the paper. At the same time, I would like to know whether darktrack2021 cannot be trained on it, and the pre-trained model you provided can be directly applied to tracking in other dark scenarios

darktrack2021      | AUC        | OP50       | OP75       | Precision    | Norm Precision    |
DCPT                      | 74.13      | 79.83      | 75.81        | 77.76             | 79.12

**Comment by bearyi26** [comment]
Hello! Thanks for reaching out. I just double checked. If you use the weights directly provided in the Google Drive, it should yield the same results as written in the paper. 

As for your questions, darktrack2021 is just a benchmark for testing and we did not include it when we trained the model. I am wondering if you use it for both training and testing. It is normal to see huge performance boost if you do so. Also, our pre-trained model can be directly applied to tracking in other dark scenarios.
