### ISSUE TITLE
Dataset download link for Shift_Night

### ISSUE THREAD

**Issue by Xuchen-Li** [bearyi26/DCPT#6]
Hello, thank you for your wonderful work.
I want to download the Shift_Night dataset to train DCPT model, but I find the format of the dataset downloaded is not structured like the annotation file in your repository.
Here is an example:
The string in the annotation file ”0003-17fb/11367“ seems to be a folder name. But in the dataset I downloaded, I can't find this folder, only find the folder named "0003-17fb".
Can you provide the download link for the Shift_Nighe dataset?
Thank you very much.

**Comment by Xuchen-Li** [comment]
I have got the answer from Dr. Zhu. Thanks for your wonderful work again!

**Comment by 24zyyyt** [comment]
> I have got the answer from Dr. Zhu. Thanks for your wonderful work again!

我也遇到这个问题了，请问可以给我也分享一份吗

**Comment by suxiaolin-collab** [comment]
你好，我也遇到这个问题，可以分享吗
